profiles/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views
from . import views

app_name = 'accounts'

urlpatterns = [
    path('login/', auth_views.LoginView.as_view(template_name='profiles/login.html'), name='login'),
    path('logout/', auth_views.LogoutView.as_view(), name='logout'),
    path('register/', views.Register.as_view(), name='register')
]

src/urls.py
"""ForestForLife URL Configuration

The 'urlpatterns' list routes URLs to views.
"""
from django.contrib import admin
from django.urls import path
from django.urls import include
from . import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.HomePage.as_view(), name='home'),
    path('profiles/', include('profiles.urls', namespace='profiles')),
    path('profiles/', include('django.contrib.auth.urls')),
    path('support/', include('support.urls', namespace='support')),
    path('explore/', views.ExplorePage.as_view(), name='explore'),
    path('about/', views.AboutPage.as_view(), name='about'),
    path('sonnygame/', views.SonnygamePage.as_view(), name='sonnygame'),
    path('data_policy', views.DataPolPage.as_view(), name='data_policy'),
    path('privacy_policy', views.PrivacyPolPage.as_view(), name='privacy_policy'),
    path('terms_and_cond', views.TnCPage.as_view(), name='terms_and_cond')

]

handler404 = 'src.views.page_not_foundPage'

support/urls.py
from django.urls import path
from . import views

app_name = 'support'

urlpatterns = [
    path('contact/', views.contact, name='contact'),
    path('success/', views.success, name='success'),
    path('donate/', views.donate, name="donate"),
    path('config/', views.stripe_config),
    path('create-checkout-session/', views.create_checkout_session),
    path('d_success/', views.d_success, name='d_success'),
    path('d_cancelled/', views.d_cancelled, name='d_cancelled')
]

profiles/models.py
from django.db import models
from django.contrib.auth.models import auth


class User(auth.models.User, auth.models.PermissionsMixin):

    def __str__(self):
        return "@{}".format(self.username)

support/models.py
from django.db import models

# Create your models here.

profiles/forms.py
from django.contrib.auth import get_user_model
from django.contrib.auth.forms import UserCreationForm


class UserRegisterForm(UserCreationForm):
    class Meta:
        fields = ('username', 'email', 'password1', 'password2')
        model = get_user_model()

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['username'].label = 'Username'
        self.fields['email'].label = "Email Address"

support/forms.py
from django import forms


class ContactForm(forms.Form):
    email = forms.EmailField(required=True)
    subject = forms.CharField(max_length=100, required=True)
    message = forms.CharField(widget=forms.Textarea, required=True)

profiles/views.py
from django.shortcuts import render
from . import forms
from django.views.generic import CreateView
from django.urls import reverse_lazy


class Register(CreateView):
    form_class = forms.UserRegisterForm
    success_url = reverse_lazy('login')
    template_name = 'profiles/register.html'

src/views.py
"""
Forest For Life Views

Links all of the template views to classes
"""

from django.shortcuts import render
from django.views.generic import TemplateView
from django.contrib.auth.mixins import LoginRequiredMixin


def page_not_foundPage(request, exception):
    return render(request, '404.html', status=404)


class HomePage(TemplateView):
    template_name = 'index.html'


class ExplorePage(TemplateView):
    template_name = 'explore.html'


class AboutPage(TemplateView):
    template_name = 'about.html'


# Requires user to be logged in in order to view
class SonnygamePage(LoginRequiredMixin, TemplateView):
    template_name = 'sonnygame.html'


class DataPolPage(TemplateView):
    template_name = 'datapolicy.html'


class PrivacyPolPage(TemplateView):
    template_name = 'privacypolicy.html'


class TnCPage(TemplateView):
    template_name = 'tnc.html'

support/views.py
from django.core.mail import send_mail, BadHeaderError
from django.http import HttpResponse
from django.shortcuts import render, redirect
from . import forms
from django.conf import settings
from django.http.response import JsonResponse
from django.views.decorators.csrf import csrf_exempt
import stripe


# Displays user with contact us form to enter information
def contact(request):
    if request.method == 'GET':
        form = forms.ContactForm()
    else:
        # Once user has sent form, data is then cleaned for security purposes
        form = forms.ContactForm(request.POST)
        if form.is_valid():
            subject = form.cleaned_data['subject']
            email = form.cleaned_data['email']
            message = form.cleaned_data['message']
            # If successful, contact us form is sent to admin email
            try:
                send_mail(subject, message, email, ['n.dawson3@newcastle.ac.uk'])
            except BadHeaderError:
                return HttpResponse('Invalid header found.')
            return redirect('support:success')
    return render(request, "email.html", {'form': form})


def success(request):
    return render(request, "success.html")


def donate(request):
    return render(request, "donate.html")


# View to handle XHR request for Stripe donations
@csrf_exempt
def stripe_config(request):
    if request.method == 'GET':
        stripe_config = {'publicKey': settings.STRIPE_PUBLISHABLE_KEY}
        return JsonResponse(stripe_config, safe=False)


# Event handler to button's click event.
@csrf_exempt
def create_checkout_session(request):
    if request.method == 'GET':
        domain_url = 'http://localhost:8000/'
        stripe.api_key = settings.STRIPE_SECRET_KEY
        try:
            # Create new Checkout Session for the order, redirecting user to appropriate page
            # if donation is successful or not
            checkout_session = stripe.checkout.Session.create(
                success_url='https://127.0.0.1:8000/' + 'support/d_success',
                cancel_url='https://127.0.0.1:8000/' + 'support/d_cancelled',
                payment_method_types=['card'],
                mode='payment',
                # Donation item information to be displayed to user
                line_items=[
                    {
                        'name': 'Plant a tree',
                        'quantity': 1,
                        'currency': 'gbp',
                        'amount': '500',
                    }
                ]
            )
            return JsonResponse({'sessionId': checkout_session['id']})
        except Exception as e:
            return JsonResponse({'error': str(e)})


def d_success(request):
    return render(request, "d_success.html")


def d_cancelled(request):
    return render(request, "d_cancelled.html")

profiles/templates/profiles/login.html
{% extends "base.html" %}
{% load django_bootstrap5 %}

{% block content %}
{% include 'includes/navbar.html' %}

    <div class="container">

        <br>

        <h1>Login</h1>
        <form method="Post">
            {% csrf_token %}
            {% bootstrap_form form %}
            <input type="submit" class="btn btn-default" value="Login">
        </form>
    </div>

    <br>
    <br>
    <br>
    <br>
    <br>
    <br>
    <br>
    <br>
    <br>
    <br>

{% endblock %}

profiles/templates/profiles/register.html
{% extends "base.html" %}
{% load django_bootstrap5 %}

{% block content %}
{% include 'includes/navbar.html' %}

    <div class="container">
        <h1>Register</h1>
        <form method="Post">
            {% csrf_token %}
            {% bootstrap_form form %}
            <input type="submit" class="btn btn-default" value="Register">
        </form>
    </div>

{% endblock %}

support/templates/d_cancelled.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
{% include 'includes/navbar.html' %}

    <div class="container">
        <div class="alert alert-warning alert-dismissible fade show" role="alert">
            <strong>Oops. Something went wrong</strong> Unfortunately your donation was unsuccessful, please ensure you
            entered your details correctly.
            <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
        </div>
        <h1 class="text-center display-6 font-weight-bold">Donation unsuccessful.</h1>

        <br>

        <p class="text-center">
            Unfortunately your donation was unsuccessful, please ensure you entered your details correctly.
        </p>
        <div class="col-1 mx-auto">
            <a class="btn btn-success mb-2" href="{% url 'support:donate' %}">Try again</a>
        </div>

        <br>

        <img class="rounded mx-auto d-block img-fluid" style="width: 640px; height: 481px"
             src="{% static 'forestforlife/img/tree.jpg' %}" alt="Planted Tree">

        <br>

        <p class="text-center">If the issue continues, please contact us.</p>
        <div class="col-1 mx-auto">
            <a class="btn btn-success" href="{% url 'support:contact' %}">Contact us</a>
        </div>
    </div>

{% endblock %}

support/templates/d_success.html
{% extends 'base.html' %}
{% load static %}
{% block style %}<link rel="stylesheet" href="{% static 'forestforlife/css/d_success.css'%}">{% endblock %}
{% block content %}
{% include 'includes/navbar.html' %}

    <div class="jumbotron jumbotron-fluid">
        <div class="container">
            <h1 class="display-6">Thank you for your donation</h1>
            <p class="lead">Your donation helps us support amazing charities that strive to end deforestation.</p>
        </div>
    </div>

    <br>

    <img class="image" src="{% static 'forestforlife/img/plant_tree.jpg' %}" alt="Planted Tree">

    <br>

    <div class="jumbotron jumbotron-fluid">
        <div class="container">
            <h1 class="lead">Don't leave your friends behind</h1>
            <h3 class="display-5">Invite friends and spread the word</h3>
            <br>
            <a href="https://twitter.com/ForestForLife2?ref_src=twsrc%5Etfw" class="twitter-follow-button"
               data-size="large" data-show-count="false">Follow @ForestForLife2</a><script async
               src="https://platform.twitter.com/widgets.js" charset="utf-8"></script>

            <iframe src="https://www.facebook.com/plugins/share_button.php?href=https%3A%2F%2Fwww.facebook.com%2F
            profile.php%3Fid%3D100076324600321&layout=button&size=large&width=77&height=28&appId"
            width="77" height="28" style="border:none;overflow:hidden" scrolling="no" frameborder="0" allow="autoplay;
            clipboard-write; encrypted-media; picture-in-picture; web-share; fullscreen"></iframe>
        </div>
    </div>

{% endblock %}

support/templates/donate.html
{% extends 'base.html' %}
{% load static %}
{% block stripe %}<script src="https://js.stripe.com/v3/"></script>{% endblock %}
{% block js %}<script src="{% static 'forestforlife/js/donate.js' %}"></script>{% endblock %}
{% block style %}<link rel="stylesheet" href="{% static 'forestforlife/css/donate.css'%}">{% endblock %}

{% block content %}
{% include 'includes/navbar.html' %}

    <section class="section">
        <div id="section_con" class="container py-4">
            <div id="jumbo" class="p-5 mb-4 bg-light border rounded-3">
                <div style="text-align: center" id="jumbo_con" class="container-fluid py-5">
                    <h1 class="display-5 fw-bold">Help save our future</h1>
                    <p class="col-md-8 fs-4">
                    <p>Through your donations, we can help support amazing charities that plant trees and help reduce
                    deforestation. Charities such as The Woodland Trust that have planted over 50 million trees
                    and revived over 34,000 hectares of woodland. For £5, you help us support amazing charities that
                    pledge to plant a tree for only £1, that's a possible <b>5 trees planted every donation</b>.
                    </p>
                    <p>We pledge to donate all money generated through this project to charities that help reduce
                        deforestation and climate change.</p>
                    <br>
                    <button class="btn btn-success btn-lg" id="submitBtn">Donate today</button>
                </div>
            </div>

            <br>

            <div class="donations_quote">
                <span>Your donation will make a difference</span>
                <br>
                <strong>Help us reduce deforestation</strong>
            </div>
            <div class="donations_banner">
                <div class="row donations_banner_info">
                    <div class="col-12 col-md-4 col-lg-4">
                        <span>3t</span>
                        There are an estimated 3 trillion trees on the planet
                    </div>
                    <div class="col-12 col-md-4 col-lg-4">
                        <span>15.3b</span>
                        An estimated 15.3 billion trees are chopped down every year.
                    </div>
                    <div class="col-12 col-md-4 col-lg-4">
                        <span>46%</span>
                        Already 46% of the worlds trees have been cleared.
                    </div>
                </div>
            </div>
        </div>
    </section>

        <br>
        <br>

{% endblock %}

support/templates/email.html
{% extends 'base.html' %}
{% load django_bootstrap5 %}
{% block content %}
{% include 'includes/navbar.html' %}

    <br>

    <div class="container">
        <h1 class="display-6 font-weight-bold">Contact Us</h1>
        <form method="post">
            {% csrf_token %}
            {% bootstrap_form form %}
            <div class="form-actions">
                <button class="btn btn-success mt-2" type="submit">Send</button>
            </div>
        </form>
    </div>

    <br>
    <br>
    <br>
    <br>
    <br>

{% endblock %}

support/templates/success.html
{% extends 'base.html' %}

{% load static %}
{% block style %}<link rel="stylesheet" href="{% static 'forestforlife/css/success.css'%}">{% endblock %}
{% block content %}
{% include 'includes/navbar.html' %}

    <div class="jumbotron jumbotron-fluid">
        <div class="container">
            <h1 class="display-6">Thank you for your message</h1>
            <p class="lead">We appreciate all the feedback and support we get from the community </p>
        </div>
    </div>

    <br>
    <img class = "image" src="{% static 'forestforlife/img/growing_tree.png' %}" alt="Growing tree">

    <br>


    <div class="col-2 mx-auto">
        <div class="row">
            <div class="col" style="text-align: center">Message us again</div>
            <div class="col" style="text-align: center">Return to the home page</div>
        </div>

        <div class="row" >
            <div class="col"><a class="btn btn-success" style="height: 60px; text-align: center"
                                href="{% url 'support:contact' %}">Contact us</a></div>
            <div class="col"><a class="btn btn-success" style="height: 60px; text-align: center"
                                href="{% url 'home' %}">Home page</a></div>
        </div>
    </div>
    <br>
    <br>
    <br>
    <br>

{% endblock %}

templates/base.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    {#---CSS---#}
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
    <title>Forest For Life</title>
    {#---Styling---#}
    {% block stripe %}{% endblock %}
    {% block js %}{% endblock%}
    <script src="https://kit.fontawesome.com/f5767d8d66.js" crossorigin="anonymous"></script>
    <link rel="stylesheet" href="{% static 'forestforlife/css/master.css'%}">
    {% block style %}{% endblock %}

</head>
<body>

{#------------#}
{#---Content--#}
{#------------#}

<div class="container-mycontent">

    {% block content %}

    {% endblock %}

</div>


{#------------#}
{#---Footer---#}
{#------------#}

<div class="footer">
    <div class="footer-content">

      <div class="footer-section about">
        <h1 class="logo-text"><span>Forest</span>For Life</h1>
        <p>
          ForestForLife is a project striving to inform the general public about the risks and concerns relating to
            climate change and deforestation. The project offers various types of informative sources, ranging from
            blogs, articles and even a game, catering to a wide audience.
        </p>

        <div class="socials">
          <p>Follow Us:</p>
          <a href="https://www.facebook.com/profile.php?id=100076324600321"><i class="fab fa-facebook"></i></a>
          <a href="https://www.instagram.com/forestforlife2033/"><i class="fab fa-instagram"></i></a>
          <a href="https://twitter.com/ForestForLife2"><i class="fab fa-twitter"></i></a>
        </div>
      </div>

      <div class="footer-section links">
        <h2>Quick Links</h2>
          <a class="nav-link" href="{% url 'about' %}">About ForestForLife</a>
          <a class="nav-link" href="{% url 'data_policy' %}">Data Retention Policy</a>
          <a class="nav-link" href="{% url 'privacy_policy' %}">Privacy Policy</a>
          <a class="nav-link" href="{% url 'terms_and_cond' %}">Terms and Conditions</a>
      </div>

      <div class="footer-section contact-form">
        <h2>Support</h2>
          <a class="nav-link" href="{% url 'support:donate' %}">Donate Now</a>
          <a class="nav-link" href="{% url 'support:contact' %}">Contact Us</a>
      </div>

    </div>

    <div class="footer-bottom">
      &copy; Copyright Team 22 2021 | Newcastle University
    </div>
  </div>

{#---Popper and JavaScript---#}
<script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.10.2/dist/umd/popper.min.js" integrity="sha384-7+zCNj/IqJ95wo16oMtfsKbZ9ccEh31eOz1HGyDuCQ6wgnyJNSYdrPa03rtR1zdB" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.min.js" integrity="sha384-QJHtvGhmr9XOIpI6YVutG+2QOK9T+ZnN4kzFN1RtK3zEFEIsxhlmWl5/YESvpZ13" crossorigin="anonymous"></script>

</body>
</html>

templates/datapolicy.html
{% extends 'base.html' %}

{% block content %}
{% include 'includes/navbar.html' %}

    <br>

    <div class="container">
        <h1 class="display-5 font-weight-bold text-center">Data Retention Policy</h1>

        <br>

        <div class="data-content" style="padding: 0 15% 0 15%">
            <p>The aim of this policy is to enable Forest For Life to manage records accordingly and in compliance with
                the General Data Protection Regulation (GDPR) and other related regulations. The policy outlines a
                framework in regards to the retention and disposal of varying different personal data. Forest For Life
                is committed to handling all data to the highest standards, ensuring compliance with GDPR.</p>

            <p>Forest For Life will store your personal data in accordance with our <a href="/privacy_policy">privacy
                policy</a> and to ensure proper data processing. The total time in which we store your data is
                dependent on the type of data and its relation to Forest For Life.</p>

            <p>If you are solely a user of the website, including associated products (Sonny's Forest), and have never
                made a donation to Forest For Life, we will retain your personal data until you either notify us that
                you no longer wish for us to do so or for no longer than 12 months following your failure to respond to
                our communications.</p>

            <p>If you have made a donation, we will retain your personal data for 3 years from the date of your last
                transaction for purposes relating to recording your donation, financial obligations (tax and auditing)
                and statistical analyses and reporting. After this time, your personal data will be deleted.</p>

            <br>

            <p>If you have a reason to believe that any of your personal information retained by Forest For Life is
                inaccurate, please contact us with your requested change.</p>

            <a href="/support/contact" class="btn btn-success">Contact us</a>

            <br>
            <br>

            <p>Last updated on <u>16</u><sup>th</sup><u> January 2022</u></p>
        </div>
    </div>

{% endblock %}

templates/includes/navbar.html
{% load static %}

{#---Navbar---#}

    <nav class='navbar navbar-expand-lg navbar-light bg-light' role="navigation" id="navbar">
        <div class="container-fluid">
                <a class="navbar-brand" style="padding-right: 5px; font-family:Arial, sans-serif" href="{% url 'home' %}">Forest For Life</a>
            <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarNav">
                <div class="navbar-nav me-auto mb-2 mb-lg-0">
                    {% if user.is_authenticated %}
                        <a class="nav-link" href="{% url 'sonnygame' %}">Sonny's Forest</a>
                        <a class="nav-link" href="{% url 'explore' %}">Explore</a>
                        <a class="nav-link" href="{% url 'about' %}">About</a>
                        <a class="nav-link" href="{% url 'support:donate' %}">Donate</a>
                        <a class="nav-link" href="{% url 'accounts:logout' %}">Logout</a>
                    {% else %}
                        <a class="nav-link" href="{% url 'accounts:register' %}">Register</a>
                        <a class="nav-link" href="{% url 'accounts:login' %}">Login</a>
                        <a class="nav-link" href="{% url 'explore' %}">Explore</a>
                        <a class="nav-link" href="{% url 'about' %}">About</a>
                        <a class="nav-link" href="{% url 'support:donate' %}">Donate</a>
                    {% endif %}
                </div>
            </div>
        </div>
    </nav>

templates/index.html
{% extends "base.html" %}
{% load static %}
{% block style %}
<link rel="stylesheet" href="{% static 'forestforlife/css/index.css' %}">
{% endblock %}

{% block content %}

    <section class="intro">

        <nav class='navbar navbar-expand-sm mt-3' id="navbar">
            <div class="container-fluid"><h3>Forest For Life</h3>
                <button class="navbar-toggler navbar-light" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="collapse navbar-collapse" id="navbarNav">
                    <div class="navbar-nav me-auto mb-2 mb-lg-0">
                        {% if user.is_authenticated %}
                            <a class="nav-link" href="{% url 'sonnygame' %}">Sonny's Game</a>
                            <a class="nav-link" href="{% url 'explore' %}">Explore</a>
                            <a class="nav-link" href="{% url 'about' %}">About</a>
                            <a class="nav-link" href="{% url 'support:donate' %}">Donate</a>
                            <a class="nav-link" href="{% url 'accounts:logout' %}">Logout</a>
                        {% else %}
                            <a class="nav-link" href="{% url 'accounts:register' %}">Register</a>
                            <a class="nav-link" href="{% url 'accounts:login' %}">Login</a>
                            <a class="nav-link" href="{% url 'explore' %}">Explore</a>
                            <a class="nav-link" href="{% url 'about' %}">About</a>
                            <a class="nav-link" href="{% url 'support:donate' %}">Donate</a>
                        {% endif %}
                    </div>
                </div>
            </div>
        </nav>

        <div class="inner">
            <div class="content">
                <h1>Forest For Life</h1>
                <figure class="text-center">
                    <blockquote class="blockquote">
                        <p>Reversing deforestation is complicated; planting trees is simple</p>
                    </blockquote>
                    <figcaption class="blockquote-footer">
                         Martin O'Malley <cite title="https://www.huffpost.com/entry/reversing-deforestation-i_b_1465102"></cite>
                    </figcaption>
                </figure>
                <a class="btn" href="/explore">Explore</a>
            </div>
        </div>
    </section>

    <br>

    <div class="card-nav container">
        <div class="row row-cols-1 row-cols-lg-3 g-4">
            <div class="col">
                <div class="card text-center">
                    <img src="{% static 'forestforlife/img/Sonny_game.png' %}" class="card-img-top" alt="...">
                    <div class="card-body">
                        <h5 class="card-title">Sonny's Forest</h5>
                        <p class="card-text">Become immersed in our tree planting game. Help us fight deforestation and stop pollution.</p>
                        <a href="/sonnygame" class="btn btn-success">Play</a>
                    </div>
                </div>
            </div>
            <div class="col">
                <div class="card text-center">
                    <img src="{% static 'forestforlife/img/explore_hp.jpg' %}" class="card-img-top" alt="...">
                    <div class="card-body">
                        <h5 class="card-title">Articles</h5>
                        <p class="card-text">Find out about all the recent news and statistics revolving around deforestation.</p>
                        <a href="/explore" class="btn btn-success">Discover</a>
                    </div>
                </div>
            </div>
            <div class="col">
                <div class="card text-center">
                    <img src="{% static 'forestforlife/img/growing_tree.jpg' %}" class="card-img-top" alt="...">
                    <div class="card-body">
                        <h5 class="card-title">Donate Today</h5>
                        <p class="card-text">Help support us in our goal of restoring the planet back to its natural beauty.</p>
                        <a href="/support/donate" class="btn btn-success">Donate</a>
                    </div>
                </div>
            </div>
        </div>
    </div>

    <br>
    <br>

    <h4 class="display-6 text-center">The UK has pledged to to be carbon neutral by 2050</h4>

    <br>

    <div class="lower container">
        <div class="row text-center align-items-center">
            <div class="col-sm-12 col-md-6 col-lg-6 order-2 order-md-1">
                <img class="img-fluid" src="{% static 'forestforlife/img/hp_tree.jpg' %}" alt="">
            </div>
            <div class="col-sm-12 col-md-6 col-lg-6 lower-text order-1 order-md-2">
                <h1>Why plant trees?</h1>
                <p>Trees absorb carbon dioxide and release oxygen, creating cleaner air and helping combat climate
                    change. They play a significant role in keeping the environment healthy by reducing pollution.
                    Planting trees play an important role in achieving the goal of net-zero greenhouse-gas emissions by
                    2050 in the UK.</p>
            </div>
        </div>
        <div class="row text-center align-items-center">
            <div class="col-sm-12 col-md-6 col-lg-6 lower-text">
                <h1>Is climate change real?</h1>
                <p>Scientific evidence for climate change is unequivocal. Ranging from the planets average surface
                 temperature rising around 1.18 degrees Celsius since the late 19th century, to the global sea level
                 rising around 8 inches in the last century; a change needs to occur. Climate change is showing no signs
                 of stopping,we need to make a stand.</p>
            </div>
            <div class="col-sm-12 col-md-6 col-lg-6">
                <img class="img-fluid" src="{% static 'forestforlife/img/hp_climate.jpg' %}" alt="">
            </div>
        </div>
        <div class="row text-center align-items-center">
            <div class="col-sm-12 col-md-6 col-lg-6 order-2 order-md-1">
                <img class="img-fluid" src="{% static 'forestforlife/img/hp_deforest.jpg' %}" alt="">
            </div>
            <div class="col-sm-12 col-md-6 col-lg-6 lower-text order-1 order-md-2">
                <h1>How bad is deforestation?</h1>
                <p>Forests cover roughly around 30 percent of the world's land area, but they are being destroyed at an
                    alarming rate. Nearly a billion acres of forest have been destroyed over the past 30 years, with
                    17% of the Amazonian rainforest being destroyed over the past 50 years. Deforestation affects both
                    people and animals with eighty percent of the planets land animals and plants living within
                    forests, threatening many species.</p>
            </div>
        </div>
    </div>

{% endblock %}